### ISSUE TITLE
Weelky 2019-11-13

### ISSUE THREAD

**Issue by damienbod** [SwissAngular/weekly#119]

**Comment by irustm** [comment]
https://github.com/irustm/angular-nodegui =)

**Comment by irustm** [comment]
https://blog.angular.io/accessibility-in-angular-e84f73a223f

**Comment by irustm** [comment]
https://netbasal.com/strategies-for-cache-busting-translation-files-in-angular-86143ee14c3c

**Comment by irustm** [comment]
https://walkingriver.com/ng-deploy-azure/ ?
