### ISSUE TITLE
weekly 2018-07-18

### ISSUE THREAD

**Issue by FabianGosebrink** [SwissAngular/weekly#72]

**Comment by damienbod** [comment]
https://speckyboy.com/css-cheatsheets-resources-guides/

https://www.softwarearchitekt.at/post/2018/07/13/angular-elements-part-i-a-dynamic-dashboard-in-four-steps-with-web-components.aspx

https://yuriburger.net/2018/07/11/angular-6-chatbot-client/

https://blogs.msdn.microsoft.com/typescript/2018/07/12/announcing-typescript-3-0-rc/

https://www.youtube.com/watch?v=Sk5jOAGl20o

https://blog.angular-university.io/rxjs-higher-order-mapping/

https://netbasal.com/introducing-akita-a-new-state-management-pattern-for-angular-applications-f2f0fab5a8

https://www.bennadel.com/blog/3471-timezone-in-date-totimestring-is-not-always-an-abbreviation-in-javascript.htm

https://www.bennadel.com/blog/3469-accessing-parent-route-params-via-paramsinheritancestrategy-in-angular-6-0-7.htm
