### ISSUE TITLE
weekly 2018-09-01

### ISSUE THREAD

**Issue by FabianGosebrink** [SwissAngular/weekly#73]
https://dzone.com/articles/simplifying-different-types-of-providers-in-angula

**Comment by damienbod** [comment]
https://angular.schule/blog/2018-02-rxjs-own-log-operator

https://netbasal.com/introducing-the-new-keyvaluepipe-in-angular-435ac2205c72

https://www.youtube.com/watch?v=jNsbB8V9u0A&feature=youtu.be&a=

https://bendyworks.com/blog/drop-20k-from-your-production-angular-app

https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

https://netbasal.com/attribute-directives-angular-forms-b40503643089
